# Generated by Django 4.2.1 on 2023-05-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_connect_tag_connect_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='date_created',
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
        migrations.DeleteModel(
            name='Connect',
        ),
    ]
