# Generated by Django 4.2.1 on 2023-05-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_tag_date_created_user_tag_delete_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.ManyToManyField(null=True, to='accounts.tag'),
        ),
    ]
